/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTrackingRouteImport } from './routes/admin/tracking'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRegionsRouteImport } from './routes/admin/regions'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminDriversRouteImport } from './routes/admin/drivers'
import { Route as AdminDeliveriesRouteImport } from './routes/admin/deliveries'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminChatRouteImport } from './routes/admin/chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrackingRoute = AdminTrackingRouteImport.update({
  id: '/admin/tracking',
  path: '/admin/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegionsRoute = AdminRegionsRouteImport.update({
  id: '/admin/regions',
  path: '/admin/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliveriesRoute = AdminDeliveriesRouteImport.update({
  id: '/admin/deliveries',
  path: '/admin/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/admin/chat',
  path: '/admin/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/chat'
    | '/admin/companies'
    | '/admin/deliveries'
    | '/admin/drivers'
    | '/admin/profile'
    | '/admin/regions'
    | '/admin/reports'
    | '/admin/tracking'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/chat'
    | '/admin/companies'
    | '/admin/deliveries'
    | '/admin/drivers'
    | '/admin/profile'
    | '/admin/regions'
    | '/admin/reports'
    | '/admin/tracking'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/chat'
    | '/admin/companies'
    | '/admin/deliveries'
    | '/admin/drivers'
    | '/admin/profile'
    | '/admin/regions'
    | '/admin/reports'
    | '/admin/tracking'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminDeliveriesRoute: typeof AdminDeliveriesRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRegionsRoute: typeof AdminRegionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminTrackingRoute: typeof AdminTrackingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tracking': {
      id: '/admin/tracking'
      path: '/admin/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AdminTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/regions': {
      id: '/admin/regions'
      path: '/admin/regions'
      fullPath: '/admin/regions'
      preLoaderRoute: typeof AdminRegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deliveries': {
      id: '/admin/deliveries'
      path: '/admin/deliveries'
      fullPath: '/admin/deliveries'
      preLoaderRoute: typeof AdminDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/admin/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminChatRoute: AdminChatRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminDeliveriesRoute: AdminDeliveriesRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRegionsRoute: AdminRegionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminTrackingRoute: AdminTrackingRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
