/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppGamesRouteImport } from './routes/app/games'
import { Route as AppFriendsRouteImport } from './routes/app/friends'
import { Route as AppDiscoverRouteImport } from './routes/app/discover'
import { Route as AppClipsRouteImport } from './routes/app/clips'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppAlbumsRouteImport } from './routes/app/albums'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRegionsRouteImport } from './routes/admin/regions'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminDriversRouteImport } from './routes/admin/drivers'
import { Route as AdminDeliveriesRouteImport } from './routes/admin/deliveries'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminChatRouteImport } from './routes/admin/chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRoute = AppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppClipsRoute = AppClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAlbumsRoute = AppAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => AppRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegionsRoute = AdminRegionsRouteImport.update({
  id: '/admin/regions',
  path: '/admin/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeliveriesRoute = AdminDeliveriesRouteImport.update({
  id: '/admin/deliveries',
  path: '/admin/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/admin/chat',
  path: '/admin/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/app/albums': typeof AppAlbumsRoute
  '/app/chat': typeof AppChatRoute
  '/app/clips': typeof AppClipsRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/games': typeof AppGamesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/app/albums': typeof AppAlbumsRoute
  '/app/chat': typeof AppChatRoute
  '/app/clips': typeof AppClipsRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/games': typeof AppGamesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/deliveries': typeof AdminDeliveriesRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/app/albums': typeof AppAlbumsRoute
  '/app/chat': typeof AppChatRoute
  '/app/clips': typeof AppClipsRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/games': typeof AppGamesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/admin/chat'
    | '/admin/companies'
    | '/admin/deliveries'
    | '/admin/drivers'
    | '/admin/profile'
    | '/admin/regions'
    | '/admin/reports'
    | '/app/albums'
    | '/app/chat'
    | '/app/clips'
    | '/app/discover'
    | '/app/friends'
    | '/app/games'
    | '/app/notifications'
    | '/app/profile'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/chat'
    | '/admin/companies'
    | '/admin/deliveries'
    | '/admin/drivers'
    | '/admin/profile'
    | '/admin/regions'
    | '/admin/reports'
    | '/app/albums'
    | '/app/chat'
    | '/app/clips'
    | '/app/discover'
    | '/app/friends'
    | '/app/games'
    | '/app/notifications'
    | '/app/profile'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/admin/chat'
    | '/admin/companies'
    | '/admin/deliveries'
    | '/admin/drivers'
    | '/admin/profile'
    | '/admin/regions'
    | '/admin/reports'
    | '/app/albums'
    | '/app/chat'
    | '/app/clips'
    | '/app/discover'
    | '/app/friends'
    | '/app/games'
    | '/app/notifications'
    | '/app/profile'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminDeliveriesRoute: typeof AdminDeliveriesRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRegionsRoute: typeof AdminRegionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/games': {
      id: '/app/games'
      path: '/games'
      fullPath: '/app/games'
      preLoaderRoute: typeof AppGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clips': {
      id: '/app/clips'
      path: '/clips'
      fullPath: '/app/clips'
      preLoaderRoute: typeof AppClipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/albums': {
      id: '/app/albums'
      path: '/albums'
      fullPath: '/app/albums'
      preLoaderRoute: typeof AppAlbumsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/regions': {
      id: '/admin/regions'
      path: '/admin/regions'
      fullPath: '/admin/regions'
      preLoaderRoute: typeof AdminRegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deliveries': {
      id: '/admin/deliveries'
      path: '/admin/deliveries'
      fullPath: '/admin/deliveries'
      preLoaderRoute: typeof AdminDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/admin/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAlbumsRoute: typeof AppAlbumsRoute
  AppChatRoute: typeof AppChatRoute
  AppClipsRoute: typeof AppClipsRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppGamesRoute: typeof AppGamesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlbumsRoute: AppAlbumsRoute,
  AppChatRoute: AppChatRoute,
  AppClipsRoute: AppClipsRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppGamesRoute: AppGamesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AdminChatRoute: AdminChatRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminDeliveriesRoute: AdminDeliveriesRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRegionsRoute: AdminRegionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
